workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
